### PR TITLE
Fixed C-c ?

### PR DESCRIPTION
**Pull request by csantosb**
Updated to latest Helm for compatibility, and re-arranged help message.

### CODE REVIEW

**Comment by michael-heerdegen** [comment]
Many thanks for your contributions!  Sorry for the long delay.

@vapniks are you able to have a look at all the proposed changes?  I think that somebody that (unlike me) actually uses recoll would do a better job than I could do here.

**Comment by michael-heerdegen** [comment]
Mmh, any of the team here who can help?

@csantosb Would you want to join the team and get write access to this repository?  Of course can I offer a second look at your commits, but I don't use recoll, so it would be good if we had someone who cares about the thing and has the little time to do so.

**Comment by csantosb** [comment]
Sure, no problem. Glad to help.

**Comment by michael-heerdegen** [comment]
Great!  If I did it correctly, you should have write access now.
I'll have a closer look at this PR later this day.

**Comment by michael-heerdegen** [comment]
Ok, most stuff looks good, see my comments on the individual commits.

It would be good if we could get rid of those calls to "eval" in addition, I can help with that if you want.

**Comment by michael-heerdegen** [comment]
But note that the main command "helm-recoll" is broken with your changes because "helm-recoll-sources-source" is undefined.

**Comment by csantosb** [comment]
Please, proceed with calls to "eval" or let me know about what exactly are you thinking about.

**Comment by vapniks** [comment]
Sorry, been busy with other things. Just got around to looking at this. 
I don't really use it much anymore either, but the new updated version seems to work fine, thanks.

**Pull request merged**
